#! /usr/bin/env python
import sys
import os
import re
if len(sys.argv) < 2:
	print('no argument! please input filename!')
else:
	try:
		f=open(sys.argv[1],'r')
		da=f.readlines()
		f.close()
	except IOError, e:
		print "*** file open error :", e
	try:
		f=open(sys.argv[1],'w')
		for eachline in da:
			f.writelines(re.sub('\,',' ',eachline))
		f.close()
	except IOError, e:
		print "*** file open error :", e
	
