#! /usr/bin/env python
import sys
import re
SearchPattern=re.compile("^\s*[0-9]* |^\+\s+")
SubPattern1=re.compile(r",")
SubPattern2=re.compile(r"^\+\s+")
SubPattern3=re.compile(r"^\s+")
SplitPattern=re.compile(r"\s+")


if len(sys.argv) < 2:
	print('no argument! please input filename!')
else:
	try:
		f=open(sys.argv[1],'r').readlines()
		da=[]
		for txt in f:
			if SearchPattern.match(txt):
				da.append(txt)	

	except IOError, e:
		print "*** file open error :", e
	try:
		f=open(sys.argv[1],'w')
		PrevText=""
		for eachline in da:
			ResLine1=SubPattern1.sub(' ',eachline)
			ResLine2=SubPattern2.sub('',ResLine1)
			ResLine=SubPattern3.sub('',ResLine2)
			SplitTemp=SplitPattern.split(ResLine)[0]
			if SplitTemp==PrevText:
				pass
			else:
				PrevText=SplitTemp
				#print ResLine
				f.writelines(ResLine)
		f.close()
	except IOError, e:
		print "*** file open error :", e
