#! /usr/bin/env python
import sys
import os
import re
if len(sys.argv) < 2:
	#print('no argument!')
	tmp=os.popen(r'find . -name "*lck"').readlines()
	for i in tmp:
		os.system('rm -f ' + i)
	#os.system('ls')
else:
	#print("first arg=",sys.argv[0])
	#print("second arg=",sys.argv[1])
	tmp=os.popen('find ' + sys.argv[1] + r' -name "*lck"').readlines()
	#print tmp
	for i in tmp:
		os.system('rm -f ' + i)
	#os.system('ls')

