#! /usr/bin/env python
import sys
import os
import re
if len(sys.argv) < 2:
	print "please input simulation filename!"
else:
	temp1=re.split(r'/',sys.argv[1])
	temp=re.split('\.',temp1[-1])
	LocalPath=r'spectremdl ++aps +mt=4 -format psfbin -batch sim_meas.mdl -tab -design ./' + temp1[-1]
	LocalPath=LocalPath + r" -measure " + temp[0] + r'.measure'
	os.system(LocalPath)